<template>
  <section class="flex min-h-0 flex-1 flex-col bg-app-bg" @click="candidateMenu = null">
    <header class="flex shrink-0 items-center justify-between border-b border-border-subtle bg-surface px-6 py-3"><div><div class="flex items-center gap-2 text-xs text-text-muted"><button @click="emit('back')">原文</button><ChevronRight :size="13" /><span>资产提取结果</span></div><p class="mt-1 text-sm font-semibold text-text-primary">{{ chapterName }}</p></div><p class="text-xs text-text-muted">基于 {{ sourceWordCount }} 字原文 · {{ candidates.length }} 项候选资产</p></header>
    <div class="flex min-h-0 flex-1">
      <aside class="custom-scrollbar w-60 shrink-0 overflow-y-auto border-r border-border-subtle bg-surface p-3"><div class="mb-3 flex items-center justify-between px-1"><span class="text-xs font-medium text-text-secondary">本次识别</span><span class="text-[11px] text-text-muted">{{ candidates.length }}/{{ candidates.length }}</span></div><template v-for="group in groups" :key="group.type"><p v-if="group.items.length" class="mb-1 mt-3 px-2 text-[11px] font-medium text-text-muted">{{ group.label }} {{ group.items.length }}</p><button v-for="candidate in group.items" :key="candidate.id" class="mb-1 flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-xs text-text-secondary hover:bg-elevated" :class="selectedId === candidate.id ? 'bg-cyan-500/12 text-text-primary' : ''" @click="selectCandidate($event, candidate.id)" @contextmenu.prevent.stop="openCandidateMenu($event, candidate.id)"><component :is="group.icon" :size="15" class="shrink-0 text-text-muted" /><span class="min-w-0 flex-1 truncate">{{ candidate.name }}</span><span class="h-1.5 w-1.5 shrink-0 rounded-full" :class="decisionColor(candidate.decision)" /></button></template></aside>
      <div v-if="activeCandidate" class="custom-scrollbar min-w-0 flex-1 overflow-y-auto"><div class="mx-auto max-w-3xl px-8 py-7"><div class="flex items-start justify-between gap-5"><div><p class="text-xs text-cyan-400">{{ typeLabel(activeCandidate.type) }} · {{ activeCandidate.importance === 'major' ? '主要资产' : '次要资产' }}</p><h2 class="mt-1 text-xl font-semibold text-text-primary">{{ activeCandidate.name }}</h2></div><div class="flex items-center gap-2"><span class="text-xs text-text-muted">本章资产</span><button class="mode-button" :class="!editing ? 'mode-button-active' : ''" @click="editing = false">预览</button><button class="mode-button" :class="editing ? 'mode-button-active' : ''" @click="editing = true">编辑</button></div></div><div class="mt-5 rounded-md border border-cyan-500/20 bg-cyan-500/5 px-4 py-3 text-xs text-text-secondary">这些内容只属于当前章节。确认后会保存到章节资产，不会自动进入项目公共资产库。</div><div class="mt-5 overflow-hidden rounded-lg border border-border-subtle bg-surface"><div class="flex items-center justify-between border-b border-border-subtle px-4 py-3"><p class="text-sm font-medium text-text-primary">资产信息</p><span class="text-[11px] text-text-muted">{{ editing ? 'Markdown 编辑' : '预览' }}</span></div><textarea v-if="editing" class="content-editor custom-scrollbar" :value="activeContent" @input="patch({ content: ($event.target as HTMLTextAreaElement).value })" placeholder="输入该资产的完整 Markdown 信息..." /><article v-else class="markdown-preview custom-scrollbar" v-html="previewHtml" /></div></div></div><div v-else class="flex flex-1 items-center justify-center text-sm text-text-muted">本次没有识别到可审核的资产</div>
    </div>
    <div v-if="candidateMenu" class="fixed z-30 min-w-40 rounded-md border border-border-subtle bg-surface p-1 shadow-xl" :style="{ left: `${candidateMenu.x}px`, top: `${candidateMenu.y}px` }" @click.stop><button v-if="canMergeCandidateStates" class="context-action" @click="mergeCandidateStates">合并选中状态</button><button v-if="selectedCandidateIds.size === 1 && activeCandidate?.visualVersion" class="context-action" @click="splitVisualVersion">拆分视觉状态</button></div>
    <footer class="flex shrink-0 items-center justify-between border-t border-border-subtle bg-surface px-6 py-3"><p class="text-xs text-text-muted">确认后保存为本章资产，之后可在资产页选择同步到公共资产库</p><div class="flex gap-3"><button class="px-3 py-2 text-xs text-text-secondary" @click="emit('back')">稍后处理</button><button class="primary-button h-9 px-4 text-xs" @click="emit('confirm')">确认本章资产</button></div></footer>
  </section>
</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { ChevronRight, MapPin, Package, UserRound } from 'lucide-vue-next'
import { v4 as uuidv4 } from 'uuid'
import type { AssetExtractionCandidateDecision, LongProjectAsset, LongProjectAssetExtractionCandidate, LongProjectAssetType } from '@comic/types'
const props = defineProps<{ chapterName: string; sourceWordCount: number; candidates: LongProjectAssetExtractionCandidate[]; assets: LongProjectAsset[] }>()
const emit = defineEmits<{ (event: 'update', candidate: LongProjectAssetExtractionCandidate): void; (event: 'add', candidate: LongProjectAssetExtractionCandidate): void; (event: 'back'): void; (event: 'confirm'): void }>()
const selectedId = ref<string | null>(props.candidates[0]?.id ?? null); const selectedCandidateIds = ref(new Set<string>()); const candidateMenu = ref<{ x: number; y: number } | null>(null); const editing = ref(false)
watch(() => props.candidates, (items) => { if (!items.some((item) => item.id === selectedId.value)) selectedId.value = items[0]?.id ?? null }, { deep: true })
watch(selectedId, () => { editing.value = false })
const activeCandidate = computed(() => props.candidates.find((item) => item.id === selectedId.value) ?? null)
const groups = computed(() => [{ type: 'character' as const, label: '人物', icon: UserRound, items: props.candidates.filter((item) => item.type === 'character') }, { type: 'scene' as const, label: '场景', icon: MapPin, items: props.candidates.filter((item) => item.type === 'scene') }, { type: 'prop' as const, label: '道具', icon: Package, items: props.candidates.filter((item) => item.type === 'prop') }])
const selectedCandidates = computed(() => props.candidates.filter((item) => selectedCandidateIds.value.has(item.id)))
const canMergeCandidateStates = computed(() => selectedCandidates.value.length >= 2 && selectedCandidates.value.every((item) => item.visualVersion) && new Set(selectedCandidates.value.map((item) => `${item.type}:${item.name.trim()}`)).size === 1)
const activeContent = computed(() => activeCandidate.value?.content || legacyContent(activeCandidate.value))
const previewHtml = computed(() => renderMarkdown(activeContent.value))
function legacyContent(candidate: LongProjectAssetExtractionCandidate | null) { if (!candidate) return ''; const lines = [...(candidate.aliases.length ? [`- 别名：${candidate.aliases.join('、')}`] : []), ...(candidate.description ? [`- 描述：${candidate.description}`] : []), ...(candidate.evidence.length ? [`- 原文依据：${candidate.evidence.join('、')}`] : [])]; if (candidate.visualVersion) lines.push(`### 视觉状态：${candidate.visualVersion.name}`, ...(candidate.visualVersion.description ? [`- 视觉描述：${candidate.visualVersion.description}`] : []), ...(candidate.visualVersion.imagePrompt ? [`- 绘画提示词：${candidate.visualVersion.imagePrompt}`] : [])); return lines.join('\n') }
function escapeHtml(value: string) { return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;') }
function renderMarkdown(value: string) { if (!value.trim()) return '<p class="empty-preview">暂无资产信息</p>'; const html: string[] = []; let list = false; const close = () => { if (list) { html.push('</ul>'); list = false } }; for (const raw of value.replace(/\r/g, '').split('\n')) { const line = raw.trim(); if (!line) { close(); continue }; const heading = line.match(/^(#{1,3})\s+(.+)$/); if (heading) { close(); html.push(`<h${heading[1].length}>${escapeHtml(heading[2])}</h${heading[1].length}>`); continue }; const bullet = line.match(/^[-*]\s+(.+)$/); if (bullet) { if (!list) { html.push('<ul>'); list = true }; html.push(`<li>${escapeHtml(bullet[1])}</li>`); continue }; close(); html.push(`<p>${escapeHtml(line)}</p>`) }; close(); return html.join('') }
function typeLabel(type: LongProjectAssetType) { return ({ character: '人物', scene: '场景', prop: '道具' })[type] }
function decisionColor(decision: AssetExtractionCandidateDecision) { return ({ create: 'bg-cyan-400', merge: 'bg-violet-400', pending: 'bg-amber-400', ignore: 'bg-slate-500' })[decision] }
function patch(change: Partial<LongProjectAssetExtractionCandidate>) { if (activeCandidate.value) emit('update', { ...activeCandidate.value, ...change }) }
function selectCandidate(event: MouseEvent, id: string) { selectedId.value = id; const next = new Set(selectedCandidateIds.value); if (event.ctrlKey || event.metaKey) next.has(id) ? next.delete(id) : next.add(id); else { next.clear(); next.add(id) }; selectedCandidateIds.value = next }
function openCandidateMenu(event: MouseEvent, id: string) { if (!selectedCandidateIds.value.has(id)) selectedCandidateIds.value = new Set([id]); selectedId.value = id; candidateMenu.value = { x: event.clientX, y: event.clientY } }
function mergeCandidateStates() { const target = selectedCandidates.value[0]; if (!target || !canMergeCandidateStates.value) return; selectedCandidates.value.slice(1).forEach((item) => emit('update', { ...item, stateParentCandidateId: target.id, stateMergeTargetCandidateId: target.id })); selectedCandidateIds.value = new Set([target.id]); candidateMenu.value = null }
function splitVisualVersion() { if (!activeCandidate.value?.visualVersion) return; const name = window.prompt('新视觉状态名称', `${activeCandidate.value.visualVersion.name} · 新状态`)?.trim(); if (!name) return; emit('add', { ...activeCandidate.value, id: uuidv4(), visualVersion: { ...activeCandidate.value.visualVersion, name }, stateParentCandidateId: activeCandidate.value.id, stateMergeTargetCandidateId: undefined, decision: 'create' }); candidateMenu.value = null }
</script>
<style scoped>
.content-editor{width:100%;border:1px solid var(--border-subtle);border-radius:.375rem;background:var(--bg-app);padding:.65rem .75rem;color:var(--text-primary);font-size:.8125rem;outline:none}.content-editor:focus{border-color:rgba(34,211,238,.55)}.content-editor{min-height:28rem;resize:vertical;line-height:1.8;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.markdown-preview{min-height:28rem;max-height:44rem;overflow-y:auto;padding:1rem 1.25rem;color:var(--text-primary);font-size:.8125rem;line-height:1.8}.markdown-preview :deep(h1),.markdown-preview :deep(h2),.markdown-preview :deep(h3){margin:1rem 0 .45rem;font-weight:600}.markdown-preview :deep(h3){color:#67e8f9}.markdown-preview :deep(p){margin:.35rem 0}.markdown-preview :deep(ul){margin:.4rem 0;padding-left:1.25rem;list-style:disc}.markdown-preview :deep(li){margin:.2rem 0}.mode-button{border-radius:.3rem;padding:.25rem .5rem;font-size:.7rem;color:var(--text-muted)}.mode-button:hover,.mode-button-active{color:#22d3ee;background:rgba(34,211,238,.1)}.primary-button{display:inline-flex;align-items:center;justify-content:center;border-radius:.375rem;background:#06b6d4;color:#020617;font-weight:500}.context-action{display:block;width:100%;padding:.55rem .75rem;text-align:left;font-size:.75rem;color:var(--text-secondary)}.context-action:hover{background:var(--bg-elevated);color:var(--text-primary)}
</style>
