<template>
  <section class="custom-scrollbar flex-1 overflow-y-auto p-6">
    <div class="mx-auto max-w-6xl">
      <div v-if="groups.some(group => group.items.length)" class="space-y-8">
        <section v-for="group in groups" :key="group.type" v-show="group.items.length">
          <div class="mb-3 flex items-center gap-2"><component :is="group.icon" :size="16" :class="group.tone" /><h3 class="text-sm font-medium text-text-primary">{{ group.label }}</h3><span class="text-xs text-text-muted">{{ group.items.length }}</span></div>
          <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            <button v-for="item in group.items" :key="`${item.entry.id}-${item.variant?.id || 'default'}`" type="button" class="asset-card" @click="openDetail(item)">
              <div v-if="item.imageUrl" class="asset-card-image"><img :src="item.imageUrl" :alt="`${item.asset.name} ${item.variant?.name || ''}`" loading="lazy" decoding="async" /><div class="asset-card-overlay" /></div>
              <div v-else class="asset-card-info"><div class="asset-card-icon"><component :is="group.icon" :size="24" :class="group.tone" /></div><p class="mt-4 text-sm font-semibold text-text-primary">{{ item.asset.name }}</p><p class="mt-1 text-xs" :class="group.tone">{{ item.variant?.name || '默认状态' }}</p><p class="mt-4 line-clamp-4 text-left text-xs leading-5 text-text-muted">{{ item.variant?.description || item.asset.description || '暂无视觉描述' }}</p><p v-if="item.variant?.tags?.length" class="mt-auto pt-3 text-left text-[10px]" :class="group.tone">{{ item.variant.tags.join(' · ') }}</p></div>
              <div class="asset-card-label" :class="item.imageUrl ? 'asset-card-label-image' : 'asset-card-label-plain'"><div class="min-w-0"><span class="block truncate font-semibold">{{ item.asset.name }}</span><span class="mt-0.5 block truncate text-[11px] opacity-70">{{ item.variant?.name || '默认状态' }}</span></div></div>
            </button>
          </div>
        </section>
      </div>
      <div v-else class="flex min-h-64 flex-col items-center justify-center text-center"><Boxes :size="28" class="text-text-muted" /><h3 class="mt-4 text-sm font-medium text-text-primary">本章还没有确认资产</h3><p class="mt-2 text-sm text-text-secondary">回到原文执行“提取资产”，审核确认后会出现在这里。</p></div>
    </div>

    <div v-if="detailItem" class="fixed inset-0 z-40 flex items-center justify-center bg-black/65 p-5" @click.self="closeDetail">
      <section class="flex max-h-[min(760px,calc(100vh-2.5rem))] w-full max-w-4xl overflow-hidden rounded-lg border border-border-subtle bg-surface shadow-2xl">
        <div class="flex w-80 shrink-0 items-center justify-center border-r border-border-subtle bg-app-bg p-5"><img v-if="detailItem.imageUrl" :src="detailItem.imageUrl" :alt="detailItem.asset.name" class="max-h-[32rem] w-full rounded-md object-contain" /><div v-else class="flex aspect-[3/4] w-full flex-col items-center justify-center rounded-md border border-border-subtle bg-surface p-6 text-center"><component :is="detailMeta.icon" :size="32" :class="detailMeta.tone" /><p class="mt-4 text-sm font-medium text-text-primary">暂无参考图</p><p class="mt-2 text-xs leading-5 text-text-muted">{{ detailItem.variant?.description || detailItem.asset.description || '请在项目资产库补充视觉参考图' }}</p></div></div>
        <div class="custom-scrollbar min-w-0 flex-1 overflow-y-auto p-6"><div class="flex items-start justify-between gap-4"><div><p class="text-xs text-text-muted">{{ detailMeta.label }} · 视觉状态</p><h2 class="mt-1 text-xl font-semibold text-text-primary">{{ detailItem.asset.name }}</h2><p class="mt-1 text-sm" :class="detailMeta.tone">{{ detailItem.variant?.name || '默认状态' }}</p></div><button class="text-text-muted hover:text-text-primary" @click="closeDetail">关闭</button></div><p class="mt-5 whitespace-pre-wrap text-sm leading-6 text-text-secondary">{{ detailItem.variant?.description || detailItem.asset.description || '暂无描述' }}</p><p v-if="detailItem.variant?.imagePrompt" class="mt-4 border-t border-border-subtle pt-4 text-xs leading-5 text-text-muted">{{ detailItem.variant.imagePrompt }}</p><p v-if="detailItem.variant?.tags?.length" class="mt-3 text-xs" :class="detailMeta.tone">{{ detailItem.variant.tags.join(' · ') }}</p>
          <div v-if="detailItem.asset.variants.length > 1" class="mt-7 border-t border-border-subtle pt-5"><div class="flex items-center justify-between"><h3 class="text-sm font-medium text-text-primary">合并视觉状态</h3><span class="text-xs text-text-muted">勾选至少两个</span></div><div class="mt-3 space-y-2"><label v-for="variant in detailItem.asset.variants" :key="variant.id" class="flex items-center gap-3 rounded-md border border-border-subtle px-3 py-2 text-xs" :class="mergeIds.has(variant.id) ? 'border-violet-400/50 bg-violet-500/10' : ''"><input v-model="mergeIdsArray" :value="variant.id" type="checkbox" class="accent-violet-400" /><span class="min-w-0 flex-1 truncate">{{ variant.name }}</span><span class="text-text-muted">{{ variant.referenceImageIds.length }} 图</span></label></div><button class="mt-3 rounded-md bg-violet-500/15 px-3 py-2 text-xs text-violet-200 disabled:opacity-40" :disabled="mergeIds.size < 2" @click="mergeDetailVariants">合并选中状态</button></div>
          <div class="mt-7 border-t border-border-subtle pt-5"><div class="flex items-center justify-between"><h3 class="text-sm font-medium text-text-primary">拆分视觉状态</h3><button class="rounded-md bg-cyan-500/15 px-3 py-2 text-xs text-cyan-200" @click="splitOpen = !splitOpen">{{ splitOpen ? '收起' : '创建新状态' }}</button></div><form v-if="splitOpen" class="mt-3 space-y-3" @submit.prevent="submitSplit"><input v-model="splitForm.name" class="form-input" placeholder="新状态名称" required /><textarea v-model="splitForm.description" class="form-input min-h-20 resize-y" placeholder="视觉描述" /><textarea v-model="splitForm.imagePrompt" class="form-input min-h-20 resize-y" placeholder="绘画提示词" /><div class="flex justify-end"><button class="primary-action" type="submit">创建状态</button></div></form></div>
        </div>
      </section>
    </div>
  </section>
</template>
<script setup lang="ts">
import { computed, reactive, ref } from 'vue'; import { Boxes, MapPin, Package, UserRound } from 'lucide-vue-next'; import type { LongProjectAsset, LongProjectAssetType, LongProjectAssetVariant, LongProjectChapterAsset } from '@comic/types';
type StateCard = { entry: LongProjectChapterAsset; asset: LongProjectAsset; variant?: LongProjectAssetVariant; imageUrl?: string }; type SplitPayload = { assetId: string; variantId: string; name: string; description: string; imagePrompt: string };
const props = defineProps<{ entries: LongProjectChapterAsset[]; assets: LongProjectAsset[] }>(); const emit = defineEmits<{ (event: 'merge-variants', value: { assetId: string; sourceVariantIds: string[]; targetVariantId: string }): void; (event: 'split-variant', value: SplitPayload): void }>(); const detailItem = ref<StateCard | null>(null); const mergeIdsArray = ref<string[]>([]); const splitOpen = ref(false); const splitForm = reactive({ name: '', description: '', imagePrompt: '' }); const meta = { character: { label: '人物', icon: UserRound, tone: 'text-cyan-400' }, scene: { label: '场景', icon: MapPin, tone: 'text-emerald-400' }, prop: { label: '道具', icon: Package, tone: 'text-amber-400' } };
const resolved = computed<StateCard[]>(() => { const cards: StateCard[] = []; for (const entry of props.entries) { const asset = props.assets.find(item => item.id === entry.assetId); if (!asset) continue; if (asset.variants.length) asset.variants.forEach(variant => cards.push({ entry, asset, variant, imageUrl: variant.referenceImageIds.find(isImageSource) })); else cards.push({ entry, asset }); } return cards }); const groups = computed(() => (Object.keys(meta) as LongProjectAssetType[]).map(type => ({ type, ...meta[type], items: resolved.value.filter(item => item.asset.type === type) }))); const mergeIds = computed(() => new Set(mergeIdsArray.value)); const detailMeta = computed(() => detailItem.value ? meta[detailItem.value.asset.type] : meta.character); function openDetail(item: StateCard) { detailItem.value = item; mergeIdsArray.value = []; splitOpen.value = false; splitForm.name = item.variant ? `${item.variant.name} · 新状态` : '新视觉状态'; splitForm.description = item.variant?.description || ''; splitForm.imagePrompt = item.variant?.imagePrompt || '' } function closeDetail() { detailItem.value = null }; function mergeDetailVariants() { const item = detailItem.value; const ids = mergeIdsArray.value; if (!item || ids.length < 2) return; emit('merge-variants', { assetId: item.asset.id, sourceVariantIds: ids.slice(1), targetVariantId: ids[0] }); mergeIdsArray.value = [ids[0]] }; function submitSplit() { const item = detailItem.value; if (!item || !splitForm.name.trim()) return; emit('split-variant', { assetId: item.asset.id, variantId: item.variant?.id || '', name: splitForm.name.trim(), description: splitForm.description.trim(), imagePrompt: splitForm.imagePrompt.trim() }); splitOpen.value = false }; function isImageSource(value: string) { return /^(https?:|data:|blob:|file:|\/)/i.test(value) }
</script>
<style scoped>
.asset-card { position:relative; display:flex; appearance:none; aspect-ratio:3 / 4; width:100%; min-width:0; flex-direction:column; overflow:hidden; border:1px solid #e5e7eb; border-radius:1rem; background:#ffffff; box-shadow:0 8px 20px rgba(15,23,42,.08),0 1px 2px rgba(15,23,42,.05); padding:0; text-align:left; transition:border-color .2s ease,transform .2s ease,box-shadow .2s ease; }
.asset-card:hover { border-color:var(--border-strong); transform:translateY(-3px); box-shadow:0 14px 28px rgba(15,23,42,.14),0 2px 5px rgba(15,23,42,.08); }
.asset-card-image { position:absolute; inset:0; overflow:hidden; background:var(--bg-elevated); }.asset-card-image img { height:100%; width:100%; object-fit:cover; transition:transform .35s ease; }.asset-card:hover .asset-card-image img { transform:scale(1.045); }.asset-card-overlay { position:absolute; inset:0; background:rgba(15,23,42,.18); }
.asset-card-info { display:flex; min-height:0; flex:1; flex-direction:column; align-items:flex-start; padding:1.15rem 1.15rem 5rem; background:#ffffff; }.asset-card-icon { display:flex; height:3.25rem; width:3.25rem; align-items:center; justify-content:center; border:1px solid #e5e7eb; border-radius:.9rem; background:#f8fafc; box-shadow:0 3px 8px rgba(15,23,42,.08); }
.asset-card-label { position:absolute; z-index:2; right:0; bottom:0; left:0; display:flex; align-items:flex-end; gap:.75rem; width:100%; box-sizing:border-box; padding:.9rem 1rem 1rem; background:transparent; font-size:.75rem; }.asset-card-label-image { color:#fff; text-shadow:0 1px 3px rgba(0,0,0,.9); }.asset-card-label-plain { color:var(--text-primary); }
.merge-row { display:flex; align-items:center; gap:.75rem; border:1px solid var(--border-subtle); border-radius:.5rem; padding:.55rem .75rem; font-size:.75rem; }.merge-row-active { border-color:var(--accent); background:color-mix(in srgb,var(--accent) 10%,transparent); }.merge-button,.split-button { border-radius:.375rem; padding:.55rem .75rem; font-size:.75rem; }.merge-button { background:color-mix(in srgb,var(--accent) 14%,transparent); color:var(--accent); }.merge-button:disabled { opacity:.4; }.split-button { background:color-mix(in srgb,var(--accent) 12%,transparent); color:var(--accent); }
.form-input { width:100%; border:1px solid var(--border-subtle); border-radius:.375rem; background:var(--bg-app); padding:.55rem .7rem; color:var(--text-primary); font-size:.8125rem; outline:none; }.form-input:focus { border-color:var(--accent); }.primary-action { border-radius:.375rem; background:var(--accent); padding:.55rem .85rem; font-size:.75rem; font-weight:500; color:#fff; }
:global(.dark) .asset-card { border-color:#334155; background:#1e293b; box-shadow:0 12px 28px rgba(2,6,23,.3),inset 0 1px 0 rgba(255,255,255,.04); }:global(.dark) .asset-card-info { background:#1e293b; }:global(.dark) .asset-card-icon { border-color:#334155; background:#0f172a; box-shadow:inset 0 1px 0 rgba(255,255,255,.05); }:global(.dark) .asset-card-overlay { background:rgba(2,6,23,.3); }:global(.dark) .asset-card-label { background:transparent; }
</style>
